-- Made by Klimp

-- First level menus
UnitPopupMenus = {
	["SELF"] = { "LOOT_METHOD", "LOOT_THRESHOLD", "LOOT_PROMOTE", "LEAVE", "RAID_TARGET_ICON", "CANCEL" },
	["PET"] = { "PET_RENAME", "PET_ABANDON", "CANCEL" },
	["PARTY"] = { "ADD_FRIEND", "WHISPER", "PROMOTE", "PROMOTE_GUIDE", "LOOT_PROMOTE", "UNINVITE", "INSPECT", "TRADE", "FOLLOW", "DUEL", "RAID_TARGET_ICON", "CANCEL" },
	["PLAYER"] = { "ADD_FRIEND",  "WHISPER", "INSPECT", "INVITE", "TRADE", "FOLLOW", "DUEL", "CANCEL" },
	["ENEMY_PLAYER"] = { },
	["RAID_PLAYER"] = { "ADD_FRIEND", "WHISPER", "PROMOTE", "PROMOTE_GUIDE", "LOOT_PROMOTE", "UNINVITE", "INSPECT", "TRADE", "FOLLOW", "DUEL", "RAID_TARGET_ICON", "CANCEL" },
	["RAID"] = { "ADD_FRIEND", "WHISPER", "PROMOTE", "PROMOTE_GUIDE", "LOOT_PROMOTE", "UNINVITE", "INSPECT", "TRADE", "FOLLOW", "DUEL", "RAID_TARGET_ICON", "CANCEL" },
	["FRIEND"] = { "WHISPER", "INVITE", "REMOVE_FRIEND", "CANCEL" },
	["FRIEND_OFFLINE"] = { "REMOVE_FRIEND", "CANCEL" },
	["BN_FRIEND"] = { "WHISPER", "BN_INVITE", "BN_REMOVE_FRIEND", "CANCEL" },
	["BN_FRIEND_OFFLINE"] = { "BN_REMOVE_FRIEND", "CANCEL" },
	["GUILD"] = { "WHISPER", "INVITE", "GUILD_PROMOTE", "TARGET", "GUILD_LEAVE", "CANCEL" },
	["GUILD_OFFLINE"] = { },
	["RAID_TARGET_ICON"] = { "RAID_TARGET_8", "RAID_TARGET_7", "RAID_TARGET_6", "RAID_TARGET_5", "RAID_TARGET_4", "RAID_TARGET_3", "RAID_TARGET_2", "RAID_TARGET_1", "RAID_TARGET_NONE" },
	["CHAT_ROSTER"] = { },
	["TARGET"] = { },
	["BOSS"] = { "RAID_TARGET_ICON", "CANCEL" },

};

