-- Made by Klimp

-- First level menus
UnitPopupMenus = {
	["SELF"] = { --[["RAID_TARGET_ICON",]] --[["SET_FOCUS",]] --[["PVP_FLAG", "LOOT_SUBSECTION_TITLE",]] "LOOT_METHOD", "LOOT_THRESHOLD", --[["OPT_OUT_LOOT_TITLE",]] "LOOT_PROMOTE", --[["INSTANCE_SUBSECTION_TITLE", "CONVERT_TO_RAID", "CONVERT_TO_PARTY", "RAID_DIFFICULTY",]] --[["RESET_INSTANCES",]] --[["OTHER_SUBSECTION_TITLE", "VOICE_CHAT", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME", "INSTANCE_LEAVE",]] "LEAVE", "RAID_TARGET_ICON", "CANCEL" },
	["PET"] = { --[["RAID_TARGET_ICON", "SET_FOCUS", "INTERACT_SUBSECTION_TITLE",]] "PET_RENAME", --[["PET_DISMISS",]] "PET_ABANDON", --[["OTHER_SUBSECTION_TITLE", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME",]] "CANCEL" },
	--["OTHERPET"] = { "RAID_TARGET_ICON", --[["SET_FOCUS", "OTHER_SUBSECTION_TITLE", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME",  "REPORT_PET",]] "CANCEL" },
	--["BATTLEPET"] = { "PET_SHOW_IN_JOURNAL", --[["SET_FOCUS",]] "OTHER_SUBSECTION_TITLE", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME", "CANCEL" },
	--["OTHERBATTLEPET"] = { "PET_SHOW_IN_JOURNAL", --[["SET_FOCUS",]] "OTHER_SUBSECTION_TITLE", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME", "REPORT_BATTLE_PET", "CANCEL" },
	["PARTY"] = { --[["RAID_TARGET_ICON",]] --[["SET_FOCUS",]] "ADD_FRIEND", --[["ADD_FRIEND_MENU", "INTERACT_SUBSECTION_TITLE", "RAF_SUMMON", "RAF_GRANT_LEVEL",]] "WHISPER", "PROMOTE", "PROMOTE_GUIDE", "LOOT_PROMOTE", "UNINVITE", "INSPECT", "TRADE", "FOLLOW", "DUEL", --[["PET_BATTLE_PVP_DUEL", "OTHER_SUBSECTION_TITLE", "VOICE_CHAT", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME", "REPORT_PLAYER", "PVP_REPORT_AFK", "VOTE_TO_KICK",]] "RAID_TARGET_ICON", "CANCEL" },
	["PLAYER"] = { --[["RAID_TARGET_ICON",]] --[["SET_FOCUS",]] "ADD_FRIEND", --[["ADD_FRIEND_MENU",]] --[["INTERACT_SUBSECTION_TITLE",]] --[["RAF_SUMMON", "RAF_GRANT_LEVEL",]] "WHISPER", --[["SUGGEST_INVITE", "REQUEST_INVITE",]] "INSPECT", "INVITE", "TRADE", "FOLLOW", "DUEL", --[["PET_BATTLE_PVP_DUEL", "OTHER_SUBSECTION_TITLE", "VOICE_CHAT", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME", "REPORT_PLAYER",]] "CANCEL" },
	--["ENEMY_PLAYER"] = {"MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME", "REPORT_PLAYER", "CANCEL"},
	["RAID_PLAYER"] = { --[["RAID_TARGET_ICON",]] --[["SET_FOCUS",]] "ADD_FRIEND", --[["ADD_FRIEND_MENU", "INTERACT_SUBSECTION_TITLE", "RAF_SUMMON", "RAF_GRANT_LEVEL",]] "WHISPER", "PROMOTE", "PROMOTE_GUIDE", "LOOT_PROMOTE", "UNINVITE", "INSPECT", "TRADE", "FOLLOW", "DUEL", --[["PET_BATTLE_PVP_DUEL", "OTHER_SUBSECTION_TITLE", "VOICE_CHAT", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME", "REPORT_PLAYER", "PVP_REPORT_AFK", "VOTE_TO_KICK",]] "RAID_TARGET_ICON", "CANCEL" },
	["RAID"] = { --[["RAID_TARGET_ICON",]] --[["SET_FOCUS",]] "ADD_FRIEND", --[["ADD_FRIEND_MENU", "INTERACT_SUBSECTION_TITLE", "RAF_SUMMON", "RAF_GRANT_LEVEL",]] "WHISPER", "PROMOTE", "PROMOTE_GUIDE", "LOOT_PROMOTE", "UNINVITE", "INSPECT", "TRADE", "FOLLOW", "DUEL", --[["PET_BATTLE_PVP_DUEL", "OTHER_SUBSECTION_TITLE", "VOICE_CHAT", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME", "REPORT_PLAYER", "PVP_REPORT_AFK", "VOTE_TO_KICK",]] "RAID_TARGET_ICON", "CANCEL" },
	["FRIEND"] = { --[["POP_OUT_CHAT", "TARGET", "SET_NOTE", "INTERACT_SUBSECTION_TITLE", "INVITE", "SUGGEST_INVITE", "REQUEST_INVITE",]] "WHISPER", "INVITE", --[["OTHER_SUBSECTION_TITLE", "DELETE_COMMUNITIES_MESSAGE", "IGNORE",]] "REMOVE_FRIEND", --[["REPORT_PLAYER", "PVP_REPORT_AFK", "TARGET",]] "CANCEL" },
	["FRIEND_OFFLINE"] = { --[["SET_NOTE", "OTHER_SUBSECTION_TITLE", "IGNORE", ]]"REMOVE_FRIEND", "CANCEL" },
	["BN_FRIEND"] = { --[["POP_OUT_CHAT", "BN_TARGET", "BN_SET_NOTE", "BN_VIEW_FRIENDS", "INTERACT_SUBSECTION_TITLE", "BN_INVITE", "BN_SUGGEST_INVITE", "BN_REQUEST_INVITE",]] "WHISPER", "BN_INVITE", --[["OTHER_SUBSECTION_TITLE", "DELETE_COMMUNITIES_MESSAGE",]] "BN_REMOVE_FRIEND", --[["REPORT_PLAYER",]] "CANCEL" },
	["BN_FRIEND_OFFLINE"] = { --[["BN_SET_NOTE", "BN_VIEW_FRIENDS", "OTHER_SUBSECTION_TITLE",]] "BN_REMOVE_FRIEND", --[["REPORT_PLAYER",]] "CANCEL" },
	["GUILD"] = { --[["TARGET", "GUILD_BATTLETAG_FRIEND", "INTERACT_SUBSECTION_TITLE",]]"WHISPER", "INVITE", --[["SUGGEST_INVITE", "REQUEST_INVITE",]] "GUILD_PROMOTE", --[["OTHER_SUBSECTION_TITLE", "VOICE_CHAT", "IGNORE",]] "TARGET", "GUILD_LEAVE", "CANCEL" },
	--["GUILD_OFFLINE"] = { "GUILD_BATTLETAG_FRIEND", "INTERACT_SUBSECTION_TITLE", "GUILD_PROMOTE", "OTHER_SUBSECTION_TITLE", "IGNORE", "GUILD_LEAVE", "CANCEL" },
	["RAID_TARGET_ICON"] = { "RAID_TARGET_8", "RAID_TARGET_7", "RAID_TARGET_6", "RAID_TARGET_5", "RAID_TARGET_4", "RAID_TARGET_3", "RAID_TARGET_2", "RAID_TARGET_1", "RAID_TARGET_NONE" },
	--["CHAT_ROSTER"] = { "VOICE_CHAT_MICROPHONE_VOLUME", "VOICE_CHAT_SPEAKER_VOLUME", "VOICE_CHAT_USER_VOLUME", "SUBSECTION_SEPARATOR", "INTERACT_SUBSECTION_TITLE", "TARGET", "WHISPER", "CHAT_OWNER", "CHAT_PROMOTE", "CHAT_DEMOTE", "SUBSECTION_SEPARATOR", "OTHER_SUBSECTION_TITLE", "REPORT_PLAYER", "VOICE_CHAT_SETTINGS", "CLOSE" },
	--["TARGET"] = { "RAID_TARGET_ICON", --[["SET_FOCUS", "ADD_FRIEND", "ADD_FRIEND_MENU", "OTHER_SUBSECTION_TITLE", "VOICE_CHAT", "MOVE_PLAYER_FRAME", "MOVE_TARGET_FRAME",]] "CANCEL" },
	["BOSS"] = { "RAID_TARGET_ICON", --[["SET_FOCUS", "OTHER_SUBSECTION_TITLE",]] "CANCEL" },

};

